version: '3.7'

services:
  theatre:

    image: app/theatre-0.0.1-snapshot

    ports:
      - "9090:9090"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

    networks:
#      Имя сети
      default:
        aliases:
#         - "localhost"
#         - "theatre"
         - "generated-reports"

networks:
  default:
    driver: bridge

#version: '3.7'
## поднимаем   grafana   и   prometheus
#services:
#  grafana:
##     grafana не готовая, а она собирается, чтобы добавить в   grafana дашборды, включенные по умолчанию
##    это дашборд с jvm и дашборд с процессом выполнения
#    build: './config/grafana'
#    ports:
#      - 3000:3000
#    volumes:
#      - ./grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    networks:
#      monitoring:
#        aliases:
#          - grafana
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9091:9091
#    volumes:
#      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus:/prometheus
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    networks:
#      monitoring:
#        aliases:
#          - prometheus
#networks:
#  monitoring: